// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CouponClaimReq struct {
	CouponId int64 `json:"coupon_id" validate:"required"`
}

type CouponClaimResp struct {
	Msg string `json:"msg"`
}

type CouponItem struct {
	Id        int64   `json:"id"`
	Name      string  `json:"name"`
	Type      int     `json:"type"`
	Threshold float64 `json:"threshold"`
	Discount  float64 `json:"discount"`
	EndTime   string  `json:"end_time"`
}

type CouponListResp struct {
	List []CouponItem `json:"list"`
}

type CouponMineReq struct {
	Status int `form:"status,default=0"`
}

type CouponMineResp struct {
	List []MyCouponItem `json:"list"`
}

type MyCouponItem struct {
	Id        int64   `json:"id"`
	CouponId  int64   `json:"coupon_id"`
	Name      string  `json:"name"`
	Threshold float64 `json:"threshold"`
	Discount  float64 `json:"discount"`
	Status    int     `json:"status"`
	EndTime   string  `json:"end_time"`
}
