// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type SearchHotResp struct {
	Keywords []string `json:"keywords"`
}

type SearchProductItem struct {
	Id    int64   `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
	Image string  `json:"image"`
}

type SearchProductReq struct {
	Keyword string `form:"keyword" validate:"required"`
	Page    int    `form:"page,default=1"`
	Size    int    `form:"size,default=20"`
}

type SearchProductResp struct {
	List  []SearchProductItem `json:"list"`
	Total int64               `json:"total"`
}

type SearchSuggestReq struct {
	Keyword string `form:"keyword" validate:"required"`
}

type SearchSuggestResp struct {
	Suggestions []string `json:"suggestions"`
}
