// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	order "go-mail/services/order/api/internal/handler/order"
	"go-mail/services/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 订单详情
				Method:  http.MethodGet,
				Path:    "/order/:id",
				Handler: order.OrderDetailHandler(serverCtx),
			},
			{
				// 取消订单
				Method:  http.MethodPost,
				Path:    "/order/cancel",
				Handler: order.CancelOrderHandler(serverCtx),
			},
			{
				// 创建订单
				Method:  http.MethodPost,
				Path:    "/order/create",
				Handler: order.CreateOrderHandler(serverCtx),
			},
			{
				// 订单列表
				Method:  http.MethodGet,
				Path:    "/order/list",
				Handler: order.OrderListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
