// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: logistics.proto

package logistics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLogisticsByOrderIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogisticsByOrderIdReq) Reset() {
	*x = GetLogisticsByOrderIdReq{}
	mi := &file_logistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogisticsByOrderIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogisticsByOrderIdReq) ProtoMessage() {}

func (x *GetLogisticsByOrderIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_logistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogisticsByOrderIdReq.ProtoReflect.Descriptor instead.
func (*GetLogisticsByOrderIdReq) Descriptor() ([]byte, []int) {
	return file_logistics_proto_rawDescGZIP(), []int{0}
}

func (x *GetLogisticsByOrderIdReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetLogisticsByOrderIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TrackingNo    string                 `protobuf:"bytes,3,opt,name=tracking_no,json=trackingNo,proto3" json:"tracking_no,omitempty"`
	Carrier       string                 `protobuf:"bytes,4,opt,name=carrier,proto3" json:"carrier,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogisticsByOrderIdResp) Reset() {
	*x = GetLogisticsByOrderIdResp{}
	mi := &file_logistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogisticsByOrderIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogisticsByOrderIdResp) ProtoMessage() {}

func (x *GetLogisticsByOrderIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_logistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogisticsByOrderIdResp.ProtoReflect.Descriptor instead.
func (*GetLogisticsByOrderIdResp) Descriptor() ([]byte, []int) {
	return file_logistics_proto_rawDescGZIP(), []int{1}
}

func (x *GetLogisticsByOrderIdResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetLogisticsByOrderIdResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetLogisticsByOrderIdResp) GetTrackingNo() string {
	if x != nil {
		return x.TrackingNo
	}
	return ""
}

func (x *GetLogisticsByOrderIdResp) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *GetLogisticsByOrderIdResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_logistics_proto protoreflect.FileDescriptor

const file_logistics_proto_rawDesc = "" +
	"\n" +
	"\x0flogistics.proto\x12\tlogistics\"5\n" +
	"\x18GetLogisticsByOrderIdReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x99\x01\n" +
	"\x19GetLogisticsByOrderIdResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1f\n" +
	"\vtracking_no\x18\x03 \x01(\tR\n" +
	"trackingNo\x12\x18\n" +
	"\acarrier\x18\x04 \x01(\tR\acarrier\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status2r\n" +
	"\fLogisticsRpc\x12b\n" +
	"\x15GetLogisticsByOrderId\x12#.logistics.GetLogisticsByOrderIdReq\x1a$.logistics.GetLogisticsByOrderIdRespB\rZ\v./logisticsb\x06proto3"

var (
	file_logistics_proto_rawDescOnce sync.Once
	file_logistics_proto_rawDescData []byte
)

func file_logistics_proto_rawDescGZIP() []byte {
	file_logistics_proto_rawDescOnce.Do(func() {
		file_logistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logistics_proto_rawDesc), len(file_logistics_proto_rawDesc)))
	})
	return file_logistics_proto_rawDescData
}

var file_logistics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_logistics_proto_goTypes = []any{
	(*GetLogisticsByOrderIdReq)(nil),  // 0: logistics.GetLogisticsByOrderIdReq
	(*GetLogisticsByOrderIdResp)(nil), // 1: logistics.GetLogisticsByOrderIdResp
}
var file_logistics_proto_depIdxs = []int32{
	0, // 0: logistics.LogisticsRpc.GetLogisticsByOrderId:input_type -> logistics.GetLogisticsByOrderIdReq
	1, // 1: logistics.LogisticsRpc.GetLogisticsByOrderId:output_type -> logistics.GetLogisticsByOrderIdResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logistics_proto_init() }
func file_logistics_proto_init() {
	if File_logistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logistics_proto_rawDesc), len(file_logistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logistics_proto_goTypes,
		DependencyIndexes: file_logistics_proto_depIdxs,
		MessageInfos:      file_logistics_proto_msgTypes,
	}.Build()
	File_logistics_proto = out.File
	file_logistics_proto_goTypes = nil
	file_logistics_proto_depIdxs = nil
}
