// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type SeckillActionReq struct {
	SkuId int64 `json:"sku_id" validate:"required"`
}

type SeckillActionResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type SeckillResultReq struct {
	SkuId int64 `form:"sku_id" validate:"required"`
}

type SeckillResultResp struct {
	Status  int    `json:"status"`
	OrderId string `json:"order_id"`
}
