// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: promotion.proto

package server

import (
	"context"

	"go-mail/services/promotion/rpc/internal/logic"
	"go-mail/services/promotion/rpc/internal/svc"
	"go-mail/services/promotion/rpc/promotion"
)

type PromotionRpcServer struct {
	svcCtx *svc.ServiceContext
	promotion.UnimplementedPromotionRpcServer
}

func NewPromotionRpcServer(svcCtx *svc.ServiceContext) *PromotionRpcServer {
	return &PromotionRpcServer{
		svcCtx: svcCtx,
	}
}

// 计算优惠价格
func (s *PromotionRpcServer) CalculateDiscount(ctx context.Context, in *promotion.CalculateDiscountReq) (*promotion.CalculateDiscountResp, error) {
	l := logic.NewCalculateDiscountLogic(ctx, s.svcCtx)
	return l.CalculateDiscount(in)
}

// 核销优惠券
func (s *PromotionRpcServer) UseCoupon(ctx context.Context, in *promotion.UseCouponReq) (*promotion.UseCouponResp, error) {
	l := logic.NewUseCouponLogic(ctx, s.svcCtx)
	return l.UseCoupon(in)
}
