// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: inventory.proto

package server

import (
	"context"

	"go-mail/services/inventory/rpc/internal/logic"
	"go-mail/services/inventory/rpc/internal/svc"
	"go-mail/services/inventory/rpc/inventory"
)

type InventoryRpcServer struct {
	svcCtx *svc.ServiceContext
	inventory.UnimplementedInventoryRpcServer
}

func NewInventoryRpcServer(svcCtx *svc.ServiceContext) *InventoryRpcServer {
	return &InventoryRpcServer{
		svcCtx: svcCtx,
	}
}

// 查询 SKU 库存
func (s *InventoryRpcServer) GetStock(ctx context.Context, in *inventory.GetStockReq) (*inventory.GetStockResp, error) {
	l := logic.NewGetStockLogic(ctx, s.svcCtx)
	return l.GetStock(in)
}

// 扣减库存（下单时调用）
func (s *InventoryRpcServer) DeductStock(ctx context.Context, in *inventory.DeductStockReq) (*inventory.DeductStockResp, error) {
	l := logic.NewDeductStockLogic(ctx, s.svcCtx)
	return l.DeductStock(in)
}

// 回滚库存（取消订单时调用）
func (s *InventoryRpcServer) RollbackStock(ctx context.Context, in *inventory.RollbackStockReq) (*inventory.RollbackStockResp, error) {
	l := logic.NewRollbackStockLogic(ctx, s.svcCtx)
	return l.RollbackStock(in)
}
