// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product.proto

package productrpc

import (
	"context"

	"go-mail/services/product/rpc/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetProductReq        = product.GetProductReq
	GetProductResp       = product.GetProductResp
	GetProductsByIdsReq  = product.GetProductsByIdsReq
	GetProductsByIdsResp = product.GetProductsByIdsResp

	ProductRpc interface {
		// 根据 ID 查询单个商品
		GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error)
		// 根据 ID 列表批量查询商品
		GetProductsByIds(ctx context.Context, in *GetProductsByIdsReq, opts ...grpc.CallOption) (*GetProductsByIdsResp, error)
	}

	defaultProductRpc struct {
		cli zrpc.Client
	}
)

func NewProductRpc(cli zrpc.Client) ProductRpc {
	return &defaultProductRpc{
		cli: cli,
	}
}

// 根据 ID 查询单个商品
func (m *defaultProductRpc) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error) {
	client := product.NewProductRpcClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}

// 根据 ID 列表批量查询商品
func (m *defaultProductRpc) GetProductsByIds(ctx context.Context, in *GetProductsByIdsReq, opts ...grpc.CallOption) (*GetProductsByIdsResp, error) {
	client := product.NewProductRpcClient(m.cli.Conn())
	return client.GetProductsByIds(ctx, in, opts...)
}
