// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	product "go-mail/services/product/api/internal/handler/product"
	"go-mail/services/product/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 商品详情（SPU+SKU 联查）
				Method:  http.MethodGet,
				Path:    "/product/:id",
				Handler: product.ProductDetailHandler(serverCtx),
			},
			{
				// 商品列表（支持分类筛选+分页）
				Method:  http.MethodGet,
				Path:    "/product/list",
				Handler: product.ProductListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
