// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: cart.proto

package cartrpc

import (
	"context"

	"go-mail/services/cart/rpc/cart"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CartItemInfo       = cart.CartItemInfo
	ClearCartItemsReq  = cart.ClearCartItemsReq
	ClearCartItemsResp = cart.ClearCartItemsResp
	GetCartItemsReq    = cart.GetCartItemsReq
	GetCartItemsResp   = cart.GetCartItemsResp

	CartRpc interface {
		// 获取用户购物车中选中的商品
		GetCartItems(ctx context.Context, in *GetCartItemsReq, opts ...grpc.CallOption) (*GetCartItemsResp, error)
		// 清空用户购物车中指定商品（下单成功后调用）
		ClearCartItems(ctx context.Context, in *ClearCartItemsReq, opts ...grpc.CallOption) (*ClearCartItemsResp, error)
	}

	defaultCartRpc struct {
		cli zrpc.Client
	}
)

func NewCartRpc(cli zrpc.Client) CartRpc {
	return &defaultCartRpc{
		cli: cli,
	}
}

// 获取用户购物车中选中的商品
func (m *defaultCartRpc) GetCartItems(ctx context.Context, in *GetCartItemsReq, opts ...grpc.CallOption) (*GetCartItemsResp, error) {
	client := cart.NewCartRpcClient(m.cli.Conn())
	return client.GetCartItems(ctx, in, opts...)
}

// 清空用户购物车中指定商品（下单成功后调用）
func (m *defaultCartRpc) ClearCartItems(ctx context.Context, in *ClearCartItemsReq, opts ...grpc.CallOption) (*ClearCartItemsResp, error) {
	client := cart.NewCartRpcClient(m.cli.Conn())
	return client.ClearCartItems(ctx, in, opts...)
}
