// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: product.proto

package server

import (
	"context"

	"go-mail/services/product/rpc/internal/logic"
	"go-mail/services/product/rpc/internal/svc"
	"go-mail/services/product/rpc/product"
)

type ProductRpcServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductRpcServer
}

func NewProductRpcServer(svcCtx *svc.ServiceContext) *ProductRpcServer {
	return &ProductRpcServer{
		svcCtx: svcCtx,
	}
}

// 根据 ID 查询单个商品
func (s *ProductRpcServer) GetProduct(ctx context.Context, in *product.GetProductReq) (*product.GetProductResp, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

// 根据 ID 列表批量查询商品
func (s *ProductRpcServer) GetProductsByIds(ctx context.Context, in *product.GetProductsByIdsReq) (*product.GetProductsByIdsResp, error) {
	l := logic.NewGetProductsByIdsLogic(ctx, s.svcCtx)
	return l.GetProductsByIds(in)
}
