// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: payment.proto

package paymentrpc

import (
	"context"

	"go-mail/services/payment/rpc/payment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetPaymentByOrderIdReq  = payment.GetPaymentByOrderIdReq
	GetPaymentByOrderIdResp = payment.GetPaymentByOrderIdResp

	PaymentRpc interface {
		// 根据订单号查询支付记录
		GetPaymentByOrderId(ctx context.Context, in *GetPaymentByOrderIdReq, opts ...grpc.CallOption) (*GetPaymentByOrderIdResp, error)
	}

	defaultPaymentRpc struct {
		cli zrpc.Client
	}
)

func NewPaymentRpc(cli zrpc.Client) PaymentRpc {
	return &defaultPaymentRpc{
		cli: cli,
	}
}

// 根据订单号查询支付记录
func (m *defaultPaymentRpc) GetPaymentByOrderId(ctx context.Context, in *GetPaymentByOrderIdReq, opts ...grpc.CallOption) (*GetPaymentByOrderIdResp, error) {
	client := payment.NewPaymentRpcClient(m.cli.Conn())
	return client.GetPaymentByOrderId(ctx, in, opts...)
}
