// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: logistics.proto

package server

import (
	"context"

	"go-mail/services/logistics/rpc/internal/logic"
	"go-mail/services/logistics/rpc/internal/svc"
	"go-mail/services/logistics/rpc/logistics"
)

type LogisticsRpcServer struct {
	svcCtx *svc.ServiceContext
	logistics.UnimplementedLogisticsRpcServer
}

func NewLogisticsRpcServer(svcCtx *svc.ServiceContext) *LogisticsRpcServer {
	return &LogisticsRpcServer{
		svcCtx: svcCtx,
	}
}

// 根据订单号查询物流
func (s *LogisticsRpcServer) GetLogisticsByOrderId(ctx context.Context, in *logistics.GetLogisticsByOrderIdReq) (*logistics.GetLogisticsByOrderIdResp, error) {
	l := logic.NewGetLogisticsByOrderIdLogic(ctx, s.svcCtx)
	return l.GetLogisticsByOrderId(in)
}
