// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: promotion.proto

package promotion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PromotionRpc_CalculateDiscount_FullMethodName = "/promotion.PromotionRpc/CalculateDiscount"
	PromotionRpc_UseCoupon_FullMethodName         = "/promotion.PromotionRpc/UseCoupon"
)

// PromotionRpcClient is the client API for PromotionRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 营销 RPC 服务 — 供 Order 调用
type PromotionRpcClient interface {
	// 计算优惠价格
	CalculateDiscount(ctx context.Context, in *CalculateDiscountReq, opts ...grpc.CallOption) (*CalculateDiscountResp, error)
	// 核销优惠券
	UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error)
}

type promotionRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewPromotionRpcClient(cc grpc.ClientConnInterface) PromotionRpcClient {
	return &promotionRpcClient{cc}
}

func (c *promotionRpcClient) CalculateDiscount(ctx context.Context, in *CalculateDiscountReq, opts ...grpc.CallOption) (*CalculateDiscountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateDiscountResp)
	err := c.cc.Invoke(ctx, PromotionRpc_CalculateDiscount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionRpcClient) UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseCouponResp)
	err := c.cc.Invoke(ctx, PromotionRpc_UseCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromotionRpcServer is the server API for PromotionRpc service.
// All implementations must embed UnimplementedPromotionRpcServer
// for forward compatibility.
//
// 营销 RPC 服务 — 供 Order 调用
type PromotionRpcServer interface {
	// 计算优惠价格
	CalculateDiscount(context.Context, *CalculateDiscountReq) (*CalculateDiscountResp, error)
	// 核销优惠券
	UseCoupon(context.Context, *UseCouponReq) (*UseCouponResp, error)
	mustEmbedUnimplementedPromotionRpcServer()
}

// UnimplementedPromotionRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromotionRpcServer struct{}

func (UnimplementedPromotionRpcServer) CalculateDiscount(context.Context, *CalculateDiscountReq) (*CalculateDiscountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateDiscount not implemented")
}
func (UnimplementedPromotionRpcServer) UseCoupon(context.Context, *UseCouponReq) (*UseCouponResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UseCoupon not implemented")
}
func (UnimplementedPromotionRpcServer) mustEmbedUnimplementedPromotionRpcServer() {}
func (UnimplementedPromotionRpcServer) testEmbeddedByValue()                      {}

// UnsafePromotionRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromotionRpcServer will
// result in compilation errors.
type UnsafePromotionRpcServer interface {
	mustEmbedUnimplementedPromotionRpcServer()
}

func RegisterPromotionRpcServer(s grpc.ServiceRegistrar, srv PromotionRpcServer) {
	// If the following call panics, it indicates UnimplementedPromotionRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PromotionRpc_ServiceDesc, srv)
}

func _PromotionRpc_CalculateDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateDiscountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionRpcServer).CalculateDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionRpc_CalculateDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionRpcServer).CalculateDiscount(ctx, req.(*CalculateDiscountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionRpc_UseCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionRpcServer).UseCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionRpc_UseCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionRpcServer).UseCoupon(ctx, req.(*UseCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PromotionRpc_ServiceDesc is the grpc.ServiceDesc for PromotionRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromotionRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "promotion.PromotionRpc",
	HandlerType: (*PromotionRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateDiscount",
			Handler:    _PromotionRpc_CalculateDiscount_Handler,
		},
		{
			MethodName: "UseCoupon",
			Handler:    _PromotionRpc_UseCoupon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "promotion.proto",
}
