// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: promotion.proto

package promotion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateDiscountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponId      int64                  `protobuf:"varint,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateDiscountReq) Reset() {
	*x = CalculateDiscountReq{}
	mi := &file_promotion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDiscountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDiscountReq) ProtoMessage() {}

func (x *CalculateDiscountReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDiscountReq.ProtoReflect.Descriptor instead.
func (*CalculateDiscountReq) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateDiscountReq) GetCouponId() int64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *CalculateDiscountReq) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type CalculateDiscountResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DiscountAmount float64                `protobuf:"fixed64,1,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	PayAmount      float64                `protobuf:"fixed64,2,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	Valid          bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CalculateDiscountResp) Reset() {
	*x = CalculateDiscountResp{}
	mi := &file_promotion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDiscountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDiscountResp) ProtoMessage() {}

func (x *CalculateDiscountResp) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDiscountResp.ProtoReflect.Descriptor instead.
func (*CalculateDiscountResp) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateDiscountResp) GetDiscountAmount() float64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *CalculateDiscountResp) GetPayAmount() float64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *CalculateDiscountResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type UseCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CouponId      int64                  `protobuf:"varint,2,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	UsedOrderId   string                 `protobuf:"bytes,3,opt,name=used_order_id,json=usedOrderId,proto3" json:"used_order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCouponReq) Reset() {
	*x = UseCouponReq{}
	mi := &file_promotion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponReq) ProtoMessage() {}

func (x *UseCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponReq.ProtoReflect.Descriptor instead.
func (*UseCouponReq) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{2}
}

func (x *UseCouponReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UseCouponReq) GetCouponId() int64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *UseCouponReq) GetUsedOrderId() string {
	if x != nil {
		return x.UsedOrderId
	}
	return ""
}

type UseCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCouponResp) Reset() {
	*x = UseCouponResp{}
	mi := &file_promotion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponResp) ProtoMessage() {}

func (x *UseCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponResp.ProtoReflect.Descriptor instead.
func (*UseCouponResp) Descriptor() ([]byte, []int) {
	return file_promotion_proto_rawDescGZIP(), []int{3}
}

func (x *UseCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_promotion_proto protoreflect.FileDescriptor

const file_promotion_proto_rawDesc = "" +
	"\n" +
	"\x0fpromotion.proto\x12\tpromotion\"V\n" +
	"\x14CalculateDiscountReq\x12\x1b\n" +
	"\tcoupon_id\x18\x01 \x01(\x03R\bcouponId\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x01R\vtotalAmount\"u\n" +
	"\x15CalculateDiscountResp\x12'\n" +
	"\x0fdiscount_amount\x18\x01 \x01(\x01R\x0ediscountAmount\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\x02 \x01(\x01R\tpayAmount\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\"h\n" +
	"\fUseCouponReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tcoupon_id\x18\x02 \x01(\x03R\bcouponId\x12\"\n" +
	"\rused_order_id\x18\x03 \x01(\tR\vusedOrderId\")\n" +
	"\rUseCouponResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa6\x01\n" +
	"\fPromotionRpc\x12V\n" +
	"\x11CalculateDiscount\x12\x1f.promotion.CalculateDiscountReq\x1a .promotion.CalculateDiscountResp\x12>\n" +
	"\tUseCoupon\x12\x17.promotion.UseCouponReq\x1a\x18.promotion.UseCouponRespB\rZ\v./promotionb\x06proto3"

var (
	file_promotion_proto_rawDescOnce sync.Once
	file_promotion_proto_rawDescData []byte
)

func file_promotion_proto_rawDescGZIP() []byte {
	file_promotion_proto_rawDescOnce.Do(func() {
		file_promotion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_promotion_proto_rawDesc), len(file_promotion_proto_rawDesc)))
	})
	return file_promotion_proto_rawDescData
}

var file_promotion_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_promotion_proto_goTypes = []any{
	(*CalculateDiscountReq)(nil),  // 0: promotion.CalculateDiscountReq
	(*CalculateDiscountResp)(nil), // 1: promotion.CalculateDiscountResp
	(*UseCouponReq)(nil),          // 2: promotion.UseCouponReq
	(*UseCouponResp)(nil),         // 3: promotion.UseCouponResp
}
var file_promotion_proto_depIdxs = []int32{
	0, // 0: promotion.PromotionRpc.CalculateDiscount:input_type -> promotion.CalculateDiscountReq
	2, // 1: promotion.PromotionRpc.UseCoupon:input_type -> promotion.UseCouponReq
	1, // 2: promotion.PromotionRpc.CalculateDiscount:output_type -> promotion.CalculateDiscountResp
	3, // 3: promotion.PromotionRpc.UseCoupon:output_type -> promotion.UseCouponResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_promotion_proto_init() }
func file_promotion_proto_init() {
	if File_promotion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_promotion_proto_rawDesc), len(file_promotion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_promotion_proto_goTypes,
		DependencyIndexes: file_promotion_proto_depIdxs,
		MessageInfos:      file_promotion_proto_msgTypes,
	}.Build()
	File_promotion_proto = out.File
	file_promotion_proto_goTypes = nil
	file_promotion_proto_depIdxs = nil
}
