// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package server

import (
	"context"

	"go-mail/services/order/rpc/internal/logic"
	"go-mail/services/order/rpc/internal/svc"
	"go-mail/services/order/rpc/order"
)

type OrderRpcServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderRpcServer
}

func NewOrderRpcServer(svcCtx *svc.ServiceContext) *OrderRpcServer {
	return &OrderRpcServer{
		svcCtx: svcCtx,
	}
}

// 查询订单
func (s *OrderRpcServer) GetOrder(ctx context.Context, in *order.GetOrderReq) (*order.GetOrderResp, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

// 更新订单状态
func (s *OrderRpcServer) UpdateOrderStatus(ctx context.Context, in *order.UpdateOrderStatusReq) (*order.UpdateOrderStatusResp, error) {
	l := logic.NewUpdateOrderStatusLogic(ctx, s.svcCtx)
	return l.UpdateOrderStatus(in)
}
