// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	search "go-mail/services/search/api/internal/handler/search"
	"go-mail/services/search/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 热搜词
				Method:  http.MethodGet,
				Path:    "/search/hot",
				Handler: search.SearchHotHandler(serverCtx),
			},
			{
				// 商品搜索
				Method:  http.MethodGet,
				Path:    "/search/product",
				Handler: search.SearchProductHandler(serverCtx),
			},
			{
				// 搜索联想
				Method:  http.MethodGet,
				Path:    "/search/suggest",
				Handler: search.SearchSuggestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
