// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: cart.proto

package server

import (
	"context"

	"go-mail/services/cart/rpc/cart"
	"go-mail/services/cart/rpc/internal/logic"
	"go-mail/services/cart/rpc/internal/svc"
)

type CartRpcServer struct {
	svcCtx *svc.ServiceContext
	cart.UnimplementedCartRpcServer
}

func NewCartRpcServer(svcCtx *svc.ServiceContext) *CartRpcServer {
	return &CartRpcServer{
		svcCtx: svcCtx,
	}
}

// 获取用户购物车中选中的商品
func (s *CartRpcServer) GetCartItems(ctx context.Context, in *cart.GetCartItemsReq) (*cart.GetCartItemsResp, error) {
	l := logic.NewGetCartItemsLogic(ctx, s.svcCtx)
	return l.GetCartItems(in)
}

// 清空用户购物车中指定商品（下单成功后调用）
func (s *CartRpcServer) ClearCartItems(ctx context.Context, in *cart.ClearCartItemsReq) (*cart.ClearCartItemsResp, error) {
	l := logic.NewClearCartItemsLogic(ctx, s.svcCtx)
	return l.ClearCartItems(in)
}
