// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	seckill "go-mail/services/seckill/api/internal/handler/seckill"
	"go-mail/services/seckill/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 执行秒杀
				Method:  http.MethodPost,
				Path:    "/seckill/action",
				Handler: seckill.SeckillActionHandler(serverCtx),
			},
			{
				// 查询秒杀结果
				Method:  http.MethodGet,
				Path:    "/seckill/result",
				Handler: seckill.SeckillResultHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
