// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ProductDetailResp struct {
	Id         int64     `json:"id"`
	Name       string    `json:"name"`
	SubTitle   string    `json:"sub_title"`
	MainImage  string    `json:"main_image"`
	DetailHtml string    `json:"detail_html"`
	Category   string    `json:"category"`
	Status     int       `json:"status"`
	Skus       []SkuItem `json:"skus"`
}

type ProductListItem struct {
	Id        int64   `json:"id"`
	Name      string  `json:"name"`
	MainImage string  `json:"main_image"`
	Price     float64 `json:"price"`
}

type ProductListReq struct {
	CategoryId int64 `form:"category_id,optional"`
	Page       int   `form:"page,default=1"`
	Size       int   `form:"size,default=20"`
}

type ProductListResp struct {
	List  []ProductListItem `json:"list"`
	Total int64             `json:"total"`
}

type SkuItem struct {
	SkuId int64   `json:"sku_id"`
	Specs string  `json:"specs"`
	Price float64 `json:"price"`
	Image string  `json:"image"`
}
