// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: logistics.proto

package logisticsrpc

import (
	"context"

	"go-mail/services/logistics/rpc/logistics"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetLogisticsByOrderIdReq  = logistics.GetLogisticsByOrderIdReq
	GetLogisticsByOrderIdResp = logistics.GetLogisticsByOrderIdResp

	LogisticsRpc interface {
		// 根据订单号查询物流
		GetLogisticsByOrderId(ctx context.Context, in *GetLogisticsByOrderIdReq, opts ...grpc.CallOption) (*GetLogisticsByOrderIdResp, error)
	}

	defaultLogisticsRpc struct {
		cli zrpc.Client
	}
)

func NewLogisticsRpc(cli zrpc.Client) LogisticsRpc {
	return &defaultLogisticsRpc{
		cli: cli,
	}
}

// 根据订单号查询物流
func (m *defaultLogisticsRpc) GetLogisticsByOrderId(ctx context.Context, in *GetLogisticsByOrderIdReq, opts ...grpc.CallOption) (*GetLogisticsByOrderIdResp, error) {
	client := logistics.NewLogisticsRpcClient(m.cli.Conn())
	return client.GetLogisticsByOrderId(ctx, in, opts...)
}
