// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type PayCallbackReq struct {
	OrderId string  `json:"order_id"`
	TradeNo string  `json:"trade_no"`
	Amount  float64 `json:"amount"`
	Status  int     `json:"status"`
}

type PayCallbackResp struct {
	Msg string `json:"msg"`
}

type PayReq struct {
	OrderId string `json:"order_id" validate:"required"`
	Channel int    `json:"channel" validate:"required"`
}

type PayResp struct {
	PayUrl string `json:"pay_url"`
}

type RefundReq struct {
	OrderId string  `json:"order_id" validate:"required"`
	Amount  float64 `json:"amount" validate:"required"`
	Reason  string  `json:"reason,optional"`
}

type RefundResp struct {
	Msg string `json:"msg"`
}
