// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userrpc

import (
	"context"

	"go-mail/services/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserByMobileReq   = user.GetUserByMobileReq
	GetUserByUsernameReq = user.GetUserByUsernameReq
	GetUserReq           = user.GetUserReq
	GetUserResp          = user.GetUserResp

	UserRpc interface {
		// 根据 ID 查询用户
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
		// 根据手机号查询用户
		GetUserByMobile(ctx context.Context, in *GetUserByMobileReq, opts ...grpc.CallOption) (*GetUserResp, error)
		// 根据用户名查询用户
		GetUserByUsername(ctx context.Context, in *GetUserByUsernameReq, opts ...grpc.CallOption) (*GetUserResp, error)
	}

	defaultUserRpc struct {
		cli zrpc.Client
	}
)

func NewUserRpc(cli zrpc.Client) UserRpc {
	return &defaultUserRpc{
		cli: cli,
	}
}

// 根据 ID 查询用户
func (m *defaultUserRpc) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := user.NewUserRpcClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

// 根据手机号查询用户
func (m *defaultUserRpc) GetUserByMobile(ctx context.Context, in *GetUserByMobileReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := user.NewUserRpcClient(m.cli.Conn())
	return client.GetUserByMobile(ctx, in, opts...)
}

// 根据用户名查询用户
func (m *defaultUserRpc) GetUserByUsername(ctx context.Context, in *GetUserByUsernameReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := user.NewUserRpcClient(m.cli.Conn())
	return client.GetUserByUsername(ctx, in, opts...)
}
