// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: payment.proto

package server

import (
	"context"

	"go-mail/services/payment/rpc/internal/logic"
	"go-mail/services/payment/rpc/internal/svc"
	"go-mail/services/payment/rpc/payment"
)

type PaymentRpcServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentRpcServer
}

func NewPaymentRpcServer(svcCtx *svc.ServiceContext) *PaymentRpcServer {
	return &PaymentRpcServer{
		svcCtx: svcCtx,
	}
}

// 根据订单号查询支付记录
func (s *PaymentRpcServer) GetPaymentByOrderId(ctx context.Context, in *payment.GetPaymentByOrderIdReq) (*payment.GetPaymentByOrderIdResp, error) {
	l := logic.NewGetPaymentByOrderIdLogic(ctx, s.svcCtx)
	return l.GetPaymentByOrderId(in)
}
