// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	payment "go-mail/services/payment/api/internal/handler/payment"
	"go-mail/services/payment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 支付回调
				Method:  http.MethodPost,
				Path:    "/payment/callback",
				Handler: payment.PayCallbackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 发起支付
				Method:  http.MethodPost,
				Path:    "/payment/pay",
				Handler: payment.PayHandler(serverCtx),
			},
			{
				// 退款
				Method:  http.MethodPost,
				Path:    "/payment/refund",
				Handler: payment.RefundHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
