// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	cart "go-mail/services/cart/api/internal/handler/cart"
	"go-mail/services/cart/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 加入购物车
				Method:  http.MethodPost,
				Path:    "/cart/add",
				Handler: cart.CartAddHandler(serverCtx),
			},
			{
				// 删除商品
				Method:  http.MethodDelete,
				Path:    "/cart/delete",
				Handler: cart.CartDeleteHandler(serverCtx),
			},
			{
				// 购物车列表
				Method:  http.MethodGet,
				Path:    "/cart/list",
				Handler: cart.CartListHandler(serverCtx),
			},
			{
				// 修改数量
				Method:  http.MethodPut,
				Path:    "/cart/update",
				Handler: cart.CartUpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
