// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package orderrpc

import (
	"context"

	"go-mail/services/order/rpc/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetOrderReq           = order.GetOrderReq
	GetOrderResp          = order.GetOrderResp
	UpdateOrderStatusReq  = order.UpdateOrderStatusReq
	UpdateOrderStatusResp = order.UpdateOrderStatusResp

	OrderRpc interface {
		// 查询订单
		GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error)
		// 更新订单状态
		UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusReq, opts ...grpc.CallOption) (*UpdateOrderStatusResp, error)
	}

	defaultOrderRpc struct {
		cli zrpc.Client
	}
)

func NewOrderRpc(cli zrpc.Client) OrderRpc {
	return &defaultOrderRpc{
		cli: cli,
	}
}

// 查询订单
func (m *defaultOrderRpc) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error) {
	client := order.NewOrderRpcClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

// 更新订单状态
func (m *defaultOrderRpc) UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusReq, opts ...grpc.CallOption) (*UpdateOrderStatusResp, error) {
	client := order.NewOrderRpcClient(m.cli.Conn())
	return client.UpdateOrderStatus(ctx, in, opts...)
}
