// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddAddressReq struct {
	Receiver  string `json:"receiver" validate:"required"`
	Phone     string `json:"phone" validate:"required,len=11"`
	Province  string `json:"province" validate:"required"`
	City      string `json:"city" validate:"required"`
	District  string `json:"district" validate:"required"`
	Detail    string `json:"detail" validate:"required"`
	IsDefault int    `json:"is_default,default=0"`
}

type AddAddressResp struct {
	Id int64 `json:"id"`
}

type AddressItem struct {
	Id        int64  `json:"id"`
	Receiver  string `json:"receiver"`
	Phone     string `json:"phone"`
	Province  string `json:"province"`
	City      string `json:"city"`
	District  string `json:"district"`
	Detail    string `json:"detail"`
	IsDefault int    `json:"is_default"`
}

type AddressListResp struct {
	List []AddressItem `json:"list"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required,min=3,max=20"`
	Password string `json:"password" validate:"required,min=6"`
	Mobile   string `json:"mobile" validate:"required,len=11"`
}

type RegisterResp struct {
	UserId int64 `json:"user_id"`
}

type UserInfoResp struct {
	Id          int64  `json:"id"`
	Username    string `json:"username"`
	Mobile      string `json:"mobile"`
	Avatar      string `json:"avatar"`
	Gender      int    `json:"gender"`
	MemberLevel int    `json:"member_level"`
}
