// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: inventory.proto

package inventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryRpc_GetStock_FullMethodName      = "/inventory.InventoryRpc/GetStock"
	InventoryRpc_DeductStock_FullMethodName   = "/inventory.InventoryRpc/DeductStock"
	InventoryRpc_RollbackStock_FullMethodName = "/inventory.InventoryRpc/RollbackStock"
)

// InventoryRpcClient is the client API for InventoryRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 库存 RPC 服务 — 仅内部调用
type InventoryRpcClient interface {
	// 查询 SKU 库存
	GetStock(ctx context.Context, in *GetStockReq, opts ...grpc.CallOption) (*GetStockResp, error)
	// 扣减库存（下单时调用）
	DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error)
	// 回滚库存（取消订单时调用）
	RollbackStock(ctx context.Context, in *RollbackStockReq, opts ...grpc.CallOption) (*RollbackStockResp, error)
}

type inventoryRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryRpcClient(cc grpc.ClientConnInterface) InventoryRpcClient {
	return &inventoryRpcClient{cc}
}

func (c *inventoryRpcClient) GetStock(ctx context.Context, in *GetStockReq, opts ...grpc.CallOption) (*GetStockResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockResp)
	err := c.cc.Invoke(ctx, InventoryRpc_GetStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryRpcClient) DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductStockResp)
	err := c.cc.Invoke(ctx, InventoryRpc_DeductStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryRpcClient) RollbackStock(ctx context.Context, in *RollbackStockReq, opts ...grpc.CallOption) (*RollbackStockResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackStockResp)
	err := c.cc.Invoke(ctx, InventoryRpc_RollbackStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryRpcServer is the server API for InventoryRpc service.
// All implementations must embed UnimplementedInventoryRpcServer
// for forward compatibility.
//
// 库存 RPC 服务 — 仅内部调用
type InventoryRpcServer interface {
	// 查询 SKU 库存
	GetStock(context.Context, *GetStockReq) (*GetStockResp, error)
	// 扣减库存（下单时调用）
	DeductStock(context.Context, *DeductStockReq) (*DeductStockResp, error)
	// 回滚库存（取消订单时调用）
	RollbackStock(context.Context, *RollbackStockReq) (*RollbackStockResp, error)
	mustEmbedUnimplementedInventoryRpcServer()
}

// UnimplementedInventoryRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryRpcServer struct{}

func (UnimplementedInventoryRpcServer) GetStock(context.Context, *GetStockReq) (*GetStockResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStock not implemented")
}
func (UnimplementedInventoryRpcServer) DeductStock(context.Context, *DeductStockReq) (*DeductStockResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductStock not implemented")
}
func (UnimplementedInventoryRpcServer) RollbackStock(context.Context, *RollbackStockReq) (*RollbackStockResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackStock not implemented")
}
func (UnimplementedInventoryRpcServer) mustEmbedUnimplementedInventoryRpcServer() {}
func (UnimplementedInventoryRpcServer) testEmbeddedByValue()                      {}

// UnsafeInventoryRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryRpcServer will
// result in compilation errors.
type UnsafeInventoryRpcServer interface {
	mustEmbedUnimplementedInventoryRpcServer()
}

func RegisterInventoryRpcServer(s grpc.ServiceRegistrar, srv InventoryRpcServer) {
	// If the following call panics, it indicates UnimplementedInventoryRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryRpc_ServiceDesc, srv)
}

func _InventoryRpc_GetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryRpcServer).GetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryRpc_GetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryRpcServer).GetStock(ctx, req.(*GetStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryRpc_DeductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryRpcServer).DeductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryRpc_DeductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryRpcServer).DeductStock(ctx, req.(*DeductStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryRpc_RollbackStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryRpcServer).RollbackStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryRpc_RollbackStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryRpcServer).RollbackStock(ctx, req.(*RollbackStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryRpc_ServiceDesc is the grpc.ServiceDesc for InventoryRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.InventoryRpc",
	HandlerType: (*InventoryRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStock",
			Handler:    _InventoryRpc_GetStock_Handler,
		},
		{
			MethodName: "DeductStock",
			Handler:    _InventoryRpc_DeductStock_Handler,
		},
		{
			MethodName: "RollbackStock",
			Handler:    _InventoryRpc_RollbackStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory.proto",
}
