// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	logistics "go-mail/services/logistics/api/internal/handler/logistics"
	"go-mail/services/logistics/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 物流详情
				Method:  http.MethodGet,
				Path:    "/logistics/detail/:id",
				Handler: logistics.LogisticsDetailHandler(serverCtx),
			},
			{
				// 发货
				Method:  http.MethodPost,
				Path:    "/logistics/send",
				Handler: logistics.ShipHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
