// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: cart.proto

package cart

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CartRpc_GetCartItems_FullMethodName   = "/cart.CartRpc/GetCartItems"
	CartRpc_ClearCartItems_FullMethodName = "/cart.CartRpc/ClearCartItems"
)

// CartRpcClient is the client API for CartRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 购物车 RPC 服务 — 供 Order 服务调用
type CartRpcClient interface {
	// 获取用户购物车中选中的商品
	GetCartItems(ctx context.Context, in *GetCartItemsReq, opts ...grpc.CallOption) (*GetCartItemsResp, error)
	// 清空用户购物车中指定商品（下单成功后调用）
	ClearCartItems(ctx context.Context, in *ClearCartItemsReq, opts ...grpc.CallOption) (*ClearCartItemsResp, error)
}

type cartRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewCartRpcClient(cc grpc.ClientConnInterface) CartRpcClient {
	return &cartRpcClient{cc}
}

func (c *cartRpcClient) GetCartItems(ctx context.Context, in *GetCartItemsReq, opts ...grpc.CallOption) (*GetCartItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCartItemsResp)
	err := c.cc.Invoke(ctx, CartRpc_GetCartItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartRpcClient) ClearCartItems(ctx context.Context, in *ClearCartItemsReq, opts ...grpc.CallOption) (*ClearCartItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearCartItemsResp)
	err := c.cc.Invoke(ctx, CartRpc_ClearCartItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartRpcServer is the server API for CartRpc service.
// All implementations must embed UnimplementedCartRpcServer
// for forward compatibility.
//
// 购物车 RPC 服务 — 供 Order 服务调用
type CartRpcServer interface {
	// 获取用户购物车中选中的商品
	GetCartItems(context.Context, *GetCartItemsReq) (*GetCartItemsResp, error)
	// 清空用户购物车中指定商品（下单成功后调用）
	ClearCartItems(context.Context, *ClearCartItemsReq) (*ClearCartItemsResp, error)
	mustEmbedUnimplementedCartRpcServer()
}

// UnimplementedCartRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCartRpcServer struct{}

func (UnimplementedCartRpcServer) GetCartItems(context.Context, *GetCartItemsReq) (*GetCartItemsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCartItems not implemented")
}
func (UnimplementedCartRpcServer) ClearCartItems(context.Context, *ClearCartItemsReq) (*ClearCartItemsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearCartItems not implemented")
}
func (UnimplementedCartRpcServer) mustEmbedUnimplementedCartRpcServer() {}
func (UnimplementedCartRpcServer) testEmbeddedByValue()                 {}

// UnsafeCartRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartRpcServer will
// result in compilation errors.
type UnsafeCartRpcServer interface {
	mustEmbedUnimplementedCartRpcServer()
}

func RegisterCartRpcServer(s grpc.ServiceRegistrar, srv CartRpcServer) {
	// If the following call panics, it indicates UnimplementedCartRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CartRpc_ServiceDesc, srv)
}

func _CartRpc_GetCartItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCartItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartRpcServer).GetCartItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartRpc_GetCartItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartRpcServer).GetCartItems(ctx, req.(*GetCartItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartRpc_ClearCartItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearCartItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartRpcServer).ClearCartItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartRpc_ClearCartItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartRpcServer).ClearCartItems(ctx, req.(*ClearCartItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CartRpc_ServiceDesc is the grpc.ServiceDesc for CartRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CartRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cart.CartRpc",
	HandlerType: (*CartRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCartItems",
			Handler:    _CartRpc_GetCartItems_Handler,
		},
		{
			MethodName: "ClearCartItems",
			Handler:    _CartRpc_ClearCartItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cart.proto",
}
