// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: cart.proto

package cart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCartItemsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartItemsReq) Reset() {
	*x = GetCartItemsReq{}
	mi := &file_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartItemsReq) ProtoMessage() {}

func (x *GetCartItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartItemsReq.ProtoReflect.Descriptor instead.
func (*GetCartItemsReq) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{0}
}

func (x *GetCartItemsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CartItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         int64                  `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	SkuSpecs      string                 `protobuf:"bytes,4,opt,name=sku_specs,json=skuSpecs,proto3" json:"sku_specs,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemInfo) Reset() {
	*x = CartItemInfo{}
	mi := &file_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemInfo) ProtoMessage() {}

func (x *CartItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemInfo.ProtoReflect.Descriptor instead.
func (*CartItemInfo) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CartItemInfo) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CartItemInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartItemInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CartItemInfo) GetSkuSpecs() string {
	if x != nil {
		return x.SkuSpecs
	}
	return ""
}

func (x *CartItemInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CartItemInfo) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetCartItemsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItemInfo        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartItemsResp) Reset() {
	*x = GetCartItemsResp{}
	mi := &file_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartItemsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartItemsResp) ProtoMessage() {}

func (x *GetCartItemsResp) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartItemsResp.ProtoReflect.Descriptor instead.
func (*GetCartItemsResp) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{2}
}

func (x *GetCartItemsResp) GetItems() []*CartItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type ClearCartItemsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkuIds        []int64                `protobuf:"varint,2,rep,packed,name=sku_ids,json=skuIds,proto3" json:"sku_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartItemsReq) Reset() {
	*x = ClearCartItemsReq{}
	mi := &file_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartItemsReq) ProtoMessage() {}

func (x *ClearCartItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartItemsReq.ProtoReflect.Descriptor instead.
func (*ClearCartItemsReq) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{3}
}

func (x *ClearCartItemsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClearCartItemsReq) GetSkuIds() []int64 {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

type ClearCartItemsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartItemsResp) Reset() {
	*x = ClearCartItemsResp{}
	mi := &file_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartItemsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartItemsResp) ProtoMessage() {}

func (x *ClearCartItemsResp) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartItemsResp.ProtoReflect.Descriptor instead.
func (*ClearCartItemsResp) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{4}
}

func (x *ClearCartItemsResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_cart_proto protoreflect.FileDescriptor

const file_cart_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"cart.proto\x12\x04cart\"*\n" +
	"\x0fGetCartItemsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xb6\x01\n" +
	"\fCartItemInfo\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x03R\x05skuId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x1b\n" +
	"\tsku_specs\x18\x04 \x01(\tR\bskuSpecs\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\"<\n" +
	"\x10GetCartItemsResp\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.cart.CartItemInfoR\x05items\"E\n" +
	"\x11ClearCartItemsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\asku_ids\x18\x02 \x03(\x03R\x06skuIds\".\n" +
	"\x12ClearCartItemsResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8d\x01\n" +
	"\aCartRpc\x12=\n" +
	"\fGetCartItems\x12\x15.cart.GetCartItemsReq\x1a\x16.cart.GetCartItemsResp\x12C\n" +
	"\x0eClearCartItems\x12\x17.cart.ClearCartItemsReq\x1a\x18.cart.ClearCartItemsRespB\bZ\x06./cartb\x06proto3"

var (
	file_cart_proto_rawDescOnce sync.Once
	file_cart_proto_rawDescData []byte
)

func file_cart_proto_rawDescGZIP() []byte {
	file_cart_proto_rawDescOnce.Do(func() {
		file_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)))
	})
	return file_cart_proto_rawDescData
}

var file_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cart_proto_goTypes = []any{
	(*GetCartItemsReq)(nil),    // 0: cart.GetCartItemsReq
	(*CartItemInfo)(nil),       // 1: cart.CartItemInfo
	(*GetCartItemsResp)(nil),   // 2: cart.GetCartItemsResp
	(*ClearCartItemsReq)(nil),  // 3: cart.ClearCartItemsReq
	(*ClearCartItemsResp)(nil), // 4: cart.ClearCartItemsResp
}
var file_cart_proto_depIdxs = []int32{
	1, // 0: cart.GetCartItemsResp.items:type_name -> cart.CartItemInfo
	0, // 1: cart.CartRpc.GetCartItems:input_type -> cart.GetCartItemsReq
	3, // 2: cart.CartRpc.ClearCartItems:input_type -> cart.ClearCartItemsReq
	2, // 3: cart.CartRpc.GetCartItems:output_type -> cart.GetCartItemsResp
	4, // 4: cart.CartRpc.ClearCartItems:output_type -> cart.ClearCartItemsResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cart_proto_init() }
func file_cart_proto_init() {
	if File_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_proto_goTypes,
		DependencyIndexes: file_cart_proto_depIdxs,
		MessageInfos:      file_cart_proto_msgTypes,
	}.Build()
	File_cart_proto = out.File
	file_cart_proto_goTypes = nil
	file_cart_proto_depIdxs = nil
}
