// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	promotion "go-mail/services/promotion/api/internal/handler/promotion"
	"go-mail/services/promotion/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 可领优惠券列表
				Method:  http.MethodGet,
				Path:    "/coupon/list",
				Handler: promotion.CouponListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 领取优惠券
				Method:  http.MethodPost,
				Path:    "/coupon/claim",
				Handler: promotion.CouponClaimHandler(serverCtx),
			},
			{
				// 我的优惠券
				Method:  http.MethodGet,
				Path:    "/coupon/mine",
				Handler: promotion.CouponMineHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
