// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"go-mail/services/user/rpc/internal/logic"
	"go-mail/services/user/rpc/internal/svc"
	"go-mail/services/user/rpc/user"
)

type UserRpcServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserRpcServer
}

func NewUserRpcServer(svcCtx *svc.ServiceContext) *UserRpcServer {
	return &UserRpcServer{
		svcCtx: svcCtx,
	}
}

// 根据 ID 查询用户
func (s *UserRpcServer) GetUser(ctx context.Context, in *user.GetUserReq) (*user.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

// 根据手机号查询用户
func (s *UserRpcServer) GetUserByMobile(ctx context.Context, in *user.GetUserByMobileReq) (*user.GetUserResp, error) {
	l := logic.NewGetUserByMobileLogic(ctx, s.svcCtx)
	return l.GetUserByMobile(in)
}

// 根据用户名查询用户
func (s *UserRpcServer) GetUserByUsername(ctx context.Context, in *user.GetUserByUsernameReq) (*user.GetUserResp, error) {
	l := logic.NewGetUserByUsernameLogic(ctx, s.svcCtx)
	return l.GetUserByUsername(in)
}
