// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CancelOrderReq struct {
	OrderId string `json:"order_id" validate:"required"`
	Reason  string `json:"reason,optional"`
}

type CancelOrderResp struct {
	Msg string `json:"msg"`
}

type CreateOrderReq struct {
	AddressId int64          `json:"address_id" validate:"required"`
	CouponId  int64          `json:"coupon_id,optional"`
	Items     []OrderItemReq `json:"items" validate:"required"`
	Remark    string         `json:"remark,optional"`
}

type CreateOrderResp struct {
	OrderId    string  `json:"order_id"`
	PayAmount  float64 `json:"pay_amount"`
	ExpireTime string  `json:"expire_time"`
}

type OrderDetailResp struct {
	OrderId        string          `json:"order_id"`
	Status         int             `json:"status"`
	TotalAmount    float64         `json:"total_amount"`
	DiscountAmount float64         `json:"discount_amount"`
	FreightAmount  float64         `json:"freight_amount"`
	PayAmount      float64         `json:"pay_amount"`
	Items          []OrderItemInfo `json:"items"`
	CreateTime     string          `json:"create_time"`
}

type OrderItemInfo struct {
	SkuId       int64   `json:"sku_id"`
	ProductName string  `json:"product_name"`
	Specs       string  `json:"specs"`
	Price       float64 `json:"price"`
	Quantity    int     `json:"quantity"`
}

type OrderItemReq struct {
	SkuId    int64 `json:"sku_id" validate:"required"`
	Quantity int   `json:"quantity" validate:"required,min=1"`
}

type OrderListItem struct {
	OrderId    string  `json:"order_id"`
	Status     int     `json:"status"`
	PayAmount  float64 `json:"pay_amount"`
	ItemCount  int     `json:"item_count"`
	CreateTime string  `json:"create_time"`
}

type OrderListReq struct {
	Status int `form:"status,default=-1"`
	Page   int `form:"page,default=1"`
	Size   int `form:"size,default=10"`
}

type OrderListResp struct {
	List  []OrderListItem `json:"list"`
	Total int64           `json:"total"`
}
