// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CartAddReq struct {
	SkuId    int64 `json:"sku_id" validate:"required"`
	Quantity int   `json:"quantity" validate:"required,min=1"`
}

type CartAddResp struct {
	Msg string `json:"msg"`
}

type CartDeleteReq struct {
	SkuIds []int64 `json:"sku_ids" validate:"required"`
}

type CartDeleteResp struct {
	Msg string `json:"msg"`
}

type CartItem struct {
	Id          int64   `json:"id"`
	SkuId       int64   `json:"sku_id"`
	ProductId   int64   `json:"product_id"`
	ProductName string  `json:"product_name"`
	Specs       string  `json:"specs"`
	Price       float64 `json:"price"`
	Quantity    int     `json:"quantity"`
	Selected    bool    `json:"selected"`
}

type CartListResp struct {
	Items       []CartItem `json:"items"`
	TotalAmount float64    `json:"total_amount"`
}

type CartUpdateReq struct {
	SkuId    int64 `json:"sku_id" validate:"required"`
	Quantity int   `json:"quantity" validate:"required,min=1"`
}

type CartUpdateResp struct {
	Msg string `json:"msg"`
}
