// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LogisticsDetailResp struct {
	OrderId    string `json:"order_id"`
	TrackingNo string `json:"tracking_no"`
	Carrier    string `json:"carrier"`
	Status     int    `json:"status"`
	CreateTime string `json:"create_time"`
}

type ShipReq struct {
	OrderId    string `json:"order_id" validate:"required"`
	Carrier    string `json:"carrier" validate:"required"`
	TrackingNo string `json:"tracking_no" validate:"required"`
}

type ShipResp struct {
	Msg string `json:"msg"`
}
