// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentRpc_GetPaymentByOrderId_FullMethodName = "/payment.PaymentRpc/GetPaymentByOrderId"
)

// PaymentRpcClient is the client API for PaymentRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 支付 RPC 服务 — 供 Order 查询支付状态
type PaymentRpcClient interface {
	// 根据订单号查询支付记录
	GetPaymentByOrderId(ctx context.Context, in *GetPaymentByOrderIdReq, opts ...grpc.CallOption) (*GetPaymentByOrderIdResp, error)
}

type paymentRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentRpcClient(cc grpc.ClientConnInterface) PaymentRpcClient {
	return &paymentRpcClient{cc}
}

func (c *paymentRpcClient) GetPaymentByOrderId(ctx context.Context, in *GetPaymentByOrderIdReq, opts ...grpc.CallOption) (*GetPaymentByOrderIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentByOrderIdResp)
	err := c.cc.Invoke(ctx, PaymentRpc_GetPaymentByOrderId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentRpcServer is the server API for PaymentRpc service.
// All implementations must embed UnimplementedPaymentRpcServer
// for forward compatibility.
//
// 支付 RPC 服务 — 供 Order 查询支付状态
type PaymentRpcServer interface {
	// 根据订单号查询支付记录
	GetPaymentByOrderId(context.Context, *GetPaymentByOrderIdReq) (*GetPaymentByOrderIdResp, error)
	mustEmbedUnimplementedPaymentRpcServer()
}

// UnimplementedPaymentRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentRpcServer struct{}

func (UnimplementedPaymentRpcServer) GetPaymentByOrderId(context.Context, *GetPaymentByOrderIdReq) (*GetPaymentByOrderIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentByOrderId not implemented")
}
func (UnimplementedPaymentRpcServer) mustEmbedUnimplementedPaymentRpcServer() {}
func (UnimplementedPaymentRpcServer) testEmbeddedByValue()                    {}

// UnsafePaymentRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentRpcServer will
// result in compilation errors.
type UnsafePaymentRpcServer interface {
	mustEmbedUnimplementedPaymentRpcServer()
}

func RegisterPaymentRpcServer(s grpc.ServiceRegistrar, srv PaymentRpcServer) {
	// If the following call panics, it indicates UnimplementedPaymentRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentRpc_ServiceDesc, srv)
}

func _PaymentRpc_GetPaymentByOrderId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentByOrderIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentRpcServer).GetPaymentByOrderId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentRpc_GetPaymentByOrderId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentRpcServer).GetPaymentByOrderId(ctx, req.(*GetPaymentByOrderIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentRpc_ServiceDesc is the grpc.ServiceDesc for PaymentRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentRpc",
	HandlerType: (*PaymentRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPaymentByOrderId",
			Handler:    _PaymentRpc_GetPaymentByOrderId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
