// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: inventory.proto

package inventoryrpc

import (
	"context"

	"go-mail/services/inventory/rpc/inventory"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeductStockReq    = inventory.DeductStockReq
	DeductStockResp   = inventory.DeductStockResp
	GetStockReq       = inventory.GetStockReq
	GetStockResp      = inventory.GetStockResp
	RollbackStockReq  = inventory.RollbackStockReq
	RollbackStockResp = inventory.RollbackStockResp

	InventoryRpc interface {
		// 查询 SKU 库存
		GetStock(ctx context.Context, in *GetStockReq, opts ...grpc.CallOption) (*GetStockResp, error)
		// 扣减库存（下单时调用）
		DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error)
		// 回滚库存（取消订单时调用）
		RollbackStock(ctx context.Context, in *RollbackStockReq, opts ...grpc.CallOption) (*RollbackStockResp, error)
	}

	defaultInventoryRpc struct {
		cli zrpc.Client
	}
)

func NewInventoryRpc(cli zrpc.Client) InventoryRpc {
	return &defaultInventoryRpc{
		cli: cli,
	}
}

// 查询 SKU 库存
func (m *defaultInventoryRpc) GetStock(ctx context.Context, in *GetStockReq, opts ...grpc.CallOption) (*GetStockResp, error) {
	client := inventory.NewInventoryRpcClient(m.cli.Conn())
	return client.GetStock(ctx, in, opts...)
}

// 扣减库存（下单时调用）
func (m *defaultInventoryRpc) DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error) {
	client := inventory.NewInventoryRpcClient(m.cli.Conn())
	return client.DeductStock(ctx, in, opts...)
}

// 回滚库存（取消订单时调用）
func (m *defaultInventoryRpc) RollbackStock(ctx context.Context, in *RollbackStockReq, opts ...grpc.CallOption) (*RollbackStockResp, error) {
	client := inventory.NewInventoryRpcClient(m.cli.Conn())
	return client.RollbackStock(ctx, in, opts...)
}
