// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: promotion.proto

package promotionrpc

import (
	"context"

	"go-mail/services/promotion/rpc/promotion"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CalculateDiscountReq  = promotion.CalculateDiscountReq
	CalculateDiscountResp = promotion.CalculateDiscountResp
	UseCouponReq          = promotion.UseCouponReq
	UseCouponResp         = promotion.UseCouponResp

	PromotionRpc interface {
		// 计算优惠价格
		CalculateDiscount(ctx context.Context, in *CalculateDiscountReq, opts ...grpc.CallOption) (*CalculateDiscountResp, error)
		// 核销优惠券
		UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error)
	}

	defaultPromotionRpc struct {
		cli zrpc.Client
	}
)

func NewPromotionRpc(cli zrpc.Client) PromotionRpc {
	return &defaultPromotionRpc{
		cli: cli,
	}
}

// 计算优惠价格
func (m *defaultPromotionRpc) CalculateDiscount(ctx context.Context, in *CalculateDiscountReq, opts ...grpc.CallOption) (*CalculateDiscountResp, error) {
	client := promotion.NewPromotionRpcClient(m.cli.Conn())
	return client.CalculateDiscount(ctx, in, opts...)
}

// 核销优惠券
func (m *defaultPromotionRpc) UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error) {
	client := promotion.NewPromotionRpcClient(m.cli.Conn())
	return client.UseCoupon(ctx, in, opts...)
}
